### ISSUE TITLE
打开任何原版都报错

### ISSUE THREAD

**Issue by 194727** [Hex-Dragon/PCL2#1035]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

任何原版下载后都报错，很郁闷
![)R)6JCGO@5IY2G7(E60PX5S](https://user-images.githubusercontent.com/123721843/215033997-20597995-8a8f-4420-ba07-77eceb722ee8.png)

### 错误报告、日志与附件

[错误报告-2023-1-27_15.07.56.zip](https://github.com/Hex-Dragon/PCL2/files/10516617/-2023-1-27_15.07.56.zip)

**Comment by 194727** [comment]
PCL下载原版后，选择版本打开就会跟图片一样，又或者弹出报错文档，尝试补全文件又或者删除重下还是一样

**Comment by youzi-2333** [comment]
无法复现，请尝试重装 Java。此处 PCL2 错误是“找不到 Minecraft”，应该也是 mc 的问题

**Comment by bwtx2023** [comment]
[Render thread/INFO] [net.optifine.Config/]: [OptiFine] java.lang.NullPointerException: Cannot read field "ofTelemetry" because "net.optifine.Config.gameSettings" is null
> 来自反馈者错误报告

怎么看起来是 OptiFine 的问题...
但是我这里安装了和反馈者一致的游戏版本、 Forge 版本、 OptiFine 版本，并未出现这个情况

**请再次确认其他启动器没有出现这个问题。** 如果其他启动器也有这个情况的话，说明不是 PCL2 问题。

你也许可以尝试卸载原先的所有 Java 17 并安装 [Azul Zulu JRE 17](https://cdn.azul.com/zulu/bin/zulu17.40.19-ca-jre17.0.6-win_x64.msi) ，之后重启 PCL2 ，再次尝试启动游戏

**Comment by 194727** [comment]
以解决，重装Java后可以修复打不开的问题，后继又出现可以打开客户端但是创建地图报错情况，经过大佬排除后发现是OptiFine和Forge不兼容，感谢大佬的帮助，谢谢
