### ISSUE TITLE
关于PCL2直接下载模组可能被启动器显示无法连接网络和报错

### ISSUE THREAD

**Issue by Judas-631139** [Hex-Dragon/PCL2#4440]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

针对一些模组（目前测试出来的，只有1.7.10版本），饰品栏和NEI物品管理器直接从PCL2下载分别会和神秘时代4和鸡块核心（也许，问题暂时未知），我通过查询外网，删除了PCL2直接下载的这些模组，接着从Curse forge下载它们，游戏可以正常启动并不会发生报错又或者其他原因

### 重现步骤

1、直接下载1.7.10的饰品栏和神秘时代4

### 日志与附件

[latest.log](https://github.com/user-attachments/files/16530616/latest.log)

**Comment by lactobionicAcid** [comment]
请上传位于 PCL 文件夹下的 Log1.txt。

**Comment by LTCatt** [comment]
请上传位于 PCL 文件夹下的 Log1~5.txt。

**Comment by JingHai-Lingyun** [comment]
> Please rephrase your problem. I read it several times and still cannot understand what you mean.

i think author means some mods that downloaded from PCL may cause crash with other mods.

> `分别会和` …… 后面是什么现象？

Crash.

---

Now waiting author upload his log.

**Comment by wuliaodexiaoluo** [comment]
>关于PCL2直接下载模组可能被启动器显示无法连接网络和报错
>日志与附件
>[latest.log](https://github.com/user-attachments/files/16530616/latest.log)

`java.lang.RuntimeException: java.lang.RuntimeException: A download error occured`
Author 应该是指这个下载错误

`at thaumcraft.codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:363) ~[%5B神秘时代%5D%20Thaumcraft-1.7.10-4.2.3.5.jar:?]`

鸡块核心在下支持库，不过看起来连通性不是很好

`Caused by: java.net.SocketTimeoutException: connect timed out`

>游戏可以正常启动并不会发生报错又或者其他原因

猜测因为之前已经下好了，第二次下载是第一次的基础+运气好连上了把缺的支持库一并下了
