### ISSUE TITLE
无法下载且无法打开1.9之后的版本

### ISSUE THREAD

**Issue by XiaoBaier599** [Hex-Dragon/PCL2#475]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自动下载中19.0 19.1 19.2版本无法和optifine或者forge一起下载，只能下载原版，而且原版下载后无法打开。用pcl2也打不开官方下载的19.0之后的版本。每次打开pcl2也都会弹获取微软正版皮肤失败。

### 重现步骤

不知道怎么触发的，本来好好的莫名其妙开始这样。不知道和我删除pcl又重新下载有关

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10101866/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10101870/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10101872/Log3.txt)
[Log4.txt](https://github.c
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10101875/Log5.txt)
om/Hex-Dragon/PCL2/files/10101874/Log4.txt)

**Comment by LTCatt** [comment]
获取微软正版皮肤失败（XiaoBaier599）：直接下载文件失败（http://textures.minecraft.net/texture/470bde342b8ec74254cf37e57c7104aface30822806da7d57f1ebb53c3e2446b）。
Caused By: 基础连接已经关闭: 接收时发生错误。
Caused By: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
Caused By: 远程主机强迫关闭了一个现有的连接。

看起来是你的网络问题。
http://textures.minecraft.net/texture/470bde342b8ec74254cf37e57c7104aface30822806da7d57f1ebb53c3e2446b 我这里是能访问的。

----

“无法下载且无法打开1.9之后的版本” 完全没有在日志里体现，你可能要重新传相关的日志或者启动失败的错误报告。
